### ISSUE TITLE
License decalaration in README.

### ISSUE THREAD

**Issue by Krrishdhaneja** [Krrishdhaneja/Friday#12]
Should I add some License details in README, or should do 
Nothing cuz I don't think so it is important.

**Comment by fm-sys** [comment]
You have the license in the project root directory, I think that should be enough...

**Comment by Krrishdhaneja** [comment]
Hey , i sent you a request to be a collaborator @fm-sys

**Comment by Krrishdhaneja** [comment]
> You have the license in the project root directory, I think that should be enough... 

Ok

**Comment by fm-sys** [comment]
> Hey , i sent you a request to be a collaborator @fm-sys

Yes, thank you
